version: '3.8'

services:
  api_mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastmcp_fastapi
    container_name: api_mcp
    ports:
      - "18000:8000"
    restart: unless-stopped