[project]
name = "understanding-starlette-sse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "starlette>=0.50.0",
    "uvicorn>=0.38.0",
]
